export const STORAGE_KEYS = {
  BOTTLES: 'dz3_bottles',
  EMPLOYEES: 'dz3_employees',
  SALES: 'dz3_sales',
  GOALS: 'dz3_goals',
  HISTORY: 'dz3_history',
};

export const CATEGORIES = ['Wine', 'Liquor'];

export const CAT_ICONS = {
  Wine: '🍷',
  Liquor: '🥃',
};

export const CAT_COLORS = {
  Wine: '#9b3a5a',
  Liquor: '#c9a227',
};

export const MEDALS = ['🥇', '🥈', '🥉'];

export const DEFAULT_EMPLOYEES = ['McKensi', 'Sheila', 'Angie', 'Tisha', 'Gaveriel', 'Sarah'];

export const DEFAULT_BOTTLES = [
  // ── Wine ──
  {
    id: 'w1',
    name: 'Jacopo Biondi-Santi',
    category: 'Wine',
    points: 12,
    bonus: 4,
    talking: [
      'Historic Tuscan estate — one of the original creators of Brunello di Montalcino.',
      'Elegant Sangiovese with dried cherry, leather, and warm spice on the finish.',
      'Perfect gift bottle — the label alone tells a story of Italian winemaking royalty.',
    ],
    pairing: 'Wild boar ragù, aged Parmigiano, or grilled lamb chops with rosemary.',
    cocktail: 'Serve at 64°F in a large Burgundy glass — decant 30 minutes for best expression.',
  },
  {
    id: 'w2',
    name: 'Goldschmidt Oakville Game Ranch',
    category: 'Wine',
    points: 16,
    bonus: 6,
    talking: [
      'Single-vineyard Cabernet from the heart of Oakville — Napa\'s most prized AVA.',
      'Big, bold dark fruit with mocha, cassis, and a velvety tannic structure.',
      'Winemaker Nick Goldschmidt hand-selects barrels — limited production each vintage.',
    ],
    pairing: 'Prime ribeye, braised short ribs, or dark chocolate torte.',
    cocktail: 'Decant 45 minutes before serving at 65°F — this wine opens up dramatically.',
  },
  {
    id: 'w3',
    name: 'Botani Muscatel Sparkling',
    category: 'Wine',
    points: 8,
    bonus: 2,
    talking: [
      'Rare sparkling Moscatel from Sierras de Málaga — crisp, dry, and aromatic.',
      'Orange blossom and lychee notes with fine persistent bubbles.',
      'Fantastic alternative to Prosecco — guests always ask what it is.',
    ],
    pairing: 'Sushi, Thai spring rolls, fresh goat cheese, or on its own as an aperitif.',
    cocktail: 'Serve ice-cold (40°F) in a flute — add a fresh basil leaf for a stunning presentation.',
  },
  {
    id: 'w4',
    name: 'Faust The Pact',
    category: 'Wine',
    points: 18,
    bonus: 7,
    talking: [
      'Coquerel Vineyard Cabernet — sister label to the iconic Quintessa estate.',
      'Layers of blackberry, graphite, and espresso with a 22-month French oak finish.',
      'Named for the Faustian bargain — the winemaker\'s deal with perfection.',
    ],
    pairing: 'Wagyu steak, truffle risotto, or aged Gruyère with fig compote.',
    cocktail: 'Decant 1 hour minimum — serve at 65°F in a Bordeaux glass.',
  },
  {
    id: 'w5',
    name: 'Laurent-Perrier Brut 375ml',
    category: 'Wine',
    points: 10,
    bonus: 3,
    talking: [
      'Family-owned Grande Marque Champagne house since 1812 — pure elegance.',
      'Citrus and white peach with a creamy mousse and crisp mineral finish.',
      'The half bottle is perfect for a Tuesday treat or a personal celebration.',
    ],
    pairing: 'Oysters, smoked salmon canapés, or buttered popcorn for a fun twist.',
    cocktail: 'Classic French 75 — gin, lemon juice, simple syrup, topped with this Champagne.',
  },
  {
    id: 'w6',
    name: 'Prisoner Chardonnay',
    category: 'Wine',
    points: 11,
    bonus: 4,
    talking: [
      'From The Prisoner Wine Company — cult Napa brand known for bold, rich wines.',
      'Tropical fruit, vanilla bean, and honey with a buttery oak finish.',
      'Great for customers who say they "don\'t like Chardonnay" — this changes minds.',
    ],
    pairing: 'Lobster mac & cheese, roasted chicken, or creamy brie with crackers.',
    cocktail: 'Serve slightly chilled at 55°F — too cold and you lose the oak complexity.',
  },
  {
    id: 'w7',
    name: 'Southern Roots Estate Cabernet',
    category: 'Wine',
    points: 9,
    bonus: 3,
    talking: [
      'Small-batch Virginia Cabernet — showcasing East Coast terroir at its best.',
      'Ripe plum, cedar, and a hint of tobacco with soft approachable tannins.',
      'Great story for customers who want to support American craft winemaking.',
    ],
    pairing: 'BBQ brisket, mushroom pizza, or sharp cheddar with crackers.',
    cocktail: 'Serve at room temp (62–65°F) — no decanting needed, drinks well immediately.',
  },
  {
    id: 'w8',
    name: 'Belaire Bleu Limited Edition',
    category: 'Wine',
    points: 12,
    bonus: 4,
    talking: [
      'Eye-catching blue LED bottle from Luc Belaire — a conversation starter.',
      'French sparkling with notes of fresh berries, white flowers, and citrus.',
      'Huge in nightlife and celebrations — the bottle lights up in the dark.',
    ],
    pairing: 'Strawberry desserts, brunch spreads, or charcuterie boards.',
    cocktail: 'Belaire Bleu Spritz — pour over ice with a splash of elderflower liqueur and a lemon twist.',
  },
  {
    id: 'w9',
    name: 'Galea Organic Mulled Wine',
    category: 'Wine',
    points: 8,
    bonus: 2,
    talking: [
      'Ready-to-heat organic mulled wine — cinnamon, clove, and orange peel already blended.',
      'Made with organic Tempranillo — no artificial flavors or sweeteners.',
      'Seasonal favorite — warm it up and serve at holiday parties in 5 minutes.',
    ],
    pairing: 'Gingerbread cookies, roasted chestnuts, or apple strudel.',
    cocktail: 'Heat gently (don\'t boil), serve in a mug with a cinnamon stick and orange wheel.',
  },
  {
    id: 'w10',
    name: 'Phelps Napa Cabernet Sauvignon',
    category: 'Wine',
    points: 14,
    bonus: 5,
    talking: [
      'Joseph Phelps — legendary Napa estate, home of the original Insignia blend.',
      'Black cherry, dark chocolate, and cedar with polished, age-worthy tannins.',
      'Consistently rated 92+ points — a benchmark Napa Cab at this price.',
    ],
    pairing: 'Filet mignon, lamb rack with herb crust, or dark chocolate truffles.',
    cocktail: 'Decant 30 minutes, serve at 65°F — pair with a great steak and good company.',
  },

  // ── Liquor ──
  {
    id: 'l1',
    name: 'Sweet Home Divided Bourbon',
    category: 'Liquor',
    points: 10,
    bonus: 3,
    talking: [
      'Alabama craft bourbon with a smooth corn-forward mash bill.',
      'Notes of caramel, toasted oak, and a hint of cinnamon on the finish.',
      'Great entry-level bourbon for customers exploring beyond mainstream brands.',
    ],
    pairing: 'Pecan pie, smoked pork ribs, or sharp cheddar with honey.',
    cocktail: 'Classic Old Fashioned — muddled sugar, Angostura bitters, orange peel, and a Luxardo cherry.',
  },
  {
    id: 'l2',
    name: 'Larceny Barrel Proof',
    category: 'Liquor',
    points: 14,
    bonus: 5,
    talking: [
      'Uncut, unfiltered wheated bourbon from Heaven Hill — big flavor, small batch.',
      'Rich butterscotch, dark fruit, and baking spice at cask strength.',
      'Wheated mash bill like Pappy — at a fraction of the price and actually in stock.',
    ],
    pairing: 'Crème brûlée, dark chocolate brownies, or smoked Gouda.',
    cocktail: 'Bourbon Smash — muddle mint and lemon, add Larceny BP, simple syrup, shake and strain over ice.',
  },
  {
    id: 'l3',
    name: 'Bumbu Rum Cream',
    category: 'Liquor',
    points: 9,
    bonus: 3,
    talking: [
      'Caribbean rum cream with real banana, vanilla, and cinnamon — dessert in a bottle.',
      'Made with Bumbu\'s award-winning XO rum base — smooth and indulgent.',
      'Perfect gift or after-dinner treat — customers buy one, then come back for three.',
    ],
    pairing: 'Banana foster, coffee cake, or vanilla ice cream as a topping.',
    cocktail: 'Bumbu Espresso — shake with fresh espresso and ice, strain into a coupe glass.',
  },
  {
    id: 'l4',
    name: 'Tres Agaves Añejo',
    category: 'Liquor',
    points: 11,
    bonus: 4,
    talking: [
      '100% blue Weber agave, aged 18 months in American oak barrels.',
      'Caramel, vanilla, and roasted agave with a warm, lingering finish.',
      'Organic and additive-free — for customers who care about clean tequila.',
    ],
    pairing: 'Mole chicken, carnitas tacos, or dark chocolate with sea salt.',
    cocktail: 'Añejo Old Fashioned — sub tequila for bourbon, add agave nectar and mole bitters.',
  },
  {
    id: 'l5',
    name: 'Four Roses Sgl Bbl OESO',
    category: 'Liquor',
    points: 13,
    bonus: 5,
    talking: [
      'Private selection single barrel — OESO is the floral, spicy recipe.',
      'Ripe red berries, allspice, and honey with a long, warm finish.',
      'Each barrel is hand-selected — when this one\'s gone, it\'s gone forever.',
    ],
    pairing: 'Apple crisp, honey-glazed ham, or aged Manchego cheese.',
    cocktail: 'Whiskey Sour — fresh lemon, simple syrup, egg white, shake hard, garnish with cherry.',
  },
  {
    id: 'l6',
    name: 'Macallan Double Cask 12yr',
    category: 'Liquor',
    points: 16,
    bonus: 6,
    talking: [
      'Macallan\'s signature sherry-seasoned American & European oak double maturation.',
      'Honey, dried fruit, and toffee with Macallan\'s trademark smoothness.',
      'The world\'s most valuable single malt brand — customers know and trust the name.',
    ],
    pairing: 'Dark chocolate, dried apricots, or smoked salmon with cream cheese.',
    cocktail: 'Serve neat or with a single large ice cube — let the sherry cask flavors shine.',
  },
  {
    id: 'l7',
    name: "Clyde May's Sgl Bbl 5yr",
    category: 'Liquor',
    points: 13,
    bonus: 4,
    talking: [
      'Alabama\'s official state spirit — single barrel, 5-year aged bourbon.',
      'Green apple, toasted vanilla, and a touch of dried fruit unique to Clyde May\'s.',
      'The apple note comes from their traditional process — it\'s subtle but distinctive.',
    ],
    pairing: 'Apple pie, pork tenderloin with apple chutney, or sharp white cheddar.',
    cocktail: 'Apple Bourbon Mule — Clyde May\'s, ginger beer, fresh lime, apple slice garnish.',
  },
  {
    id: 'l8',
    name: 'Calumet Farm 10yr',
    category: 'Liquor',
    points: 15,
    bonus: 5,
    talking: [
      'From the legendary Kentucky horse farm — 10-year single rack bourbon.',
      'Deep caramel, dark cherry, leather, and toasted pecan with a long finish.',
      'Beautiful presentation bottle — looks like a $150 bourbon, priced much lower.',
    ],
    pairing: 'Pecan-crusted salmon, bourbon bread pudding, or a fine cigar.',
    cocktail: 'Boulevardier — equal parts Calumet 10yr, sweet vermouth, and Campari, stirred and strained.',
  },
  {
    id: 'l9',
    name: 'Wilderness Tears Sgl Wheat',
    category: 'Liquor',
    points: 12,
    bonus: 4,
    talking: [
      'Single grain wheat whiskey — soft, sweet, and incredibly approachable.',
      'Honey, fresh bread, and vanilla cream with zero burn on the finish.',
      'Great crossover bottle — wine drinkers and non-whiskey drinkers love this.',
    ],
    pairing: 'Lemon tart, light salads with goat cheese, or fresh fruit and honey.',
    cocktail: 'Whiskey Lemonade — Wilderness Tears, fresh lemonade, splash of lavender syrup, garnish with thyme.',
  },
  {
    id: 'l10',
    name: 'Rabbit Hole Dareringer 92',
    category: 'Liquor',
    points: 17,
    bonus: 6,
    talking: [
      'PX sherry cask-finished bourbon — founder Kaveh Zamanian\'s personal favorite.',
      'Fig, dark chocolate, orange zest, and raisin with a sherry-sweet finish.',
      'The sherry finish makes this unlike any other bourbon on the shelf — a true standout.',
    ],
    pairing: 'Fig and prosciutto flatbread, dark chocolate mousse, or blue cheese with walnuts.',
    cocktail: 'Sherry Manhattan — Rabbit Hole Dareringer, sweet vermouth, Angostura, Luxardo cherry.',
  },
];
